# Generated by Django 2.2.12 on 2022-02-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220218_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coverphoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/coverphoto')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
