# Generated by Django 2.2.12 on 2022-02-18 21:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_coverphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverphoto',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
