# Generated by Django 2.2.12 on 2022-02-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_coverphoto_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
