# Generated by Django 2.2.12 on 2022-02-20 08:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20220219_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
